/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif



#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  jenv->ExceptionClear();
  excep = jenv->FindClass(except_ptr->java_exception);
  if (excep)
    jenv->ThrowNew(excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include <./VisLimit.h>


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void JNICALL Java_com_projectpluto_astro_astroJNI_FixedBrightnessData_1zenithAngMoon_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  FixedBrightnessData *arg1 = (FixedBrightnessData *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(FixedBrightnessData **)&jarg1; 
  arg2 = (double)jarg2; 
  if (arg1) (arg1)->zenithAngMoon = arg2;
}


SWIGEXPORT jdouble JNICALL Java_com_projectpluto_astro_astroJNI_FixedBrightnessData_1zenithAngMoon_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  FixedBrightnessData *arg1 = (FixedBrightnessData *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(FixedBrightnessData **)&jarg1; 
  result = (double) ((arg1)->zenithAngMoon);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_projectpluto_astro_astroJNI_FixedBrightnessData_1zenithAngSun_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  FixedBrightnessData *arg1 = (FixedBrightnessData *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(FixedBrightnessData **)&jarg1; 
  arg2 = (double)jarg2; 
  if (arg1) (arg1)->zenithAngSun = arg2;
}


SWIGEXPORT jdouble JNICALL Java_com_projectpluto_astro_astroJNI_FixedBrightnessData_1zenithAngSun_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  FixedBrightnessData *arg1 = (FixedBrightnessData *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(FixedBrightnessData **)&jarg1; 
  result = (double) ((arg1)->zenithAngSun);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_projectpluto_astro_astroJNI_FixedBrightnessData_1moonElongation_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  FixedBrightnessData *arg1 = (FixedBrightnessData *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(FixedBrightnessData **)&jarg1; 
  arg2 = (double)jarg2; 
  if (arg1) (arg1)->moonElongation = arg2;
}


SWIGEXPORT jdouble JNICALL Java_com_projectpluto_astro_astroJNI_FixedBrightnessData_1moonElongation_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  FixedBrightnessData *arg1 = (FixedBrightnessData *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(FixedBrightnessData **)&jarg1; 
  result = (double) ((arg1)->moonElongation);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_projectpluto_astro_astroJNI_FixedBrightnessData_1htAboveSeaInMeters_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  FixedBrightnessData *arg1 = (FixedBrightnessData *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(FixedBrightnessData **)&jarg1; 
  arg2 = (double)jarg2; 
  if (arg1) (arg1)->htAboveSeaInMeters = arg2;
}


SWIGEXPORT jdouble JNICALL Java_com_projectpluto_astro_astroJNI_FixedBrightnessData_1htAboveSeaInMeters_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  FixedBrightnessData *arg1 = (FixedBrightnessData *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(FixedBrightnessData **)&jarg1; 
  result = (double) ((arg1)->htAboveSeaInMeters);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_projectpluto_astro_astroJNI_FixedBrightnessData_1latitude_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  FixedBrightnessData *arg1 = (FixedBrightnessData *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(FixedBrightnessData **)&jarg1; 
  arg2 = (double)jarg2; 
  if (arg1) (arg1)->latitude = arg2;
}


SWIGEXPORT jdouble JNICALL Java_com_projectpluto_astro_astroJNI_FixedBrightnessData_1latitude_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  FixedBrightnessData *arg1 = (FixedBrightnessData *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(FixedBrightnessData **)&jarg1; 
  result = (double) ((arg1)->latitude);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_projectpluto_astro_astroJNI_FixedBrightnessData_1temperatureInC_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  FixedBrightnessData *arg1 = (FixedBrightnessData *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(FixedBrightnessData **)&jarg1; 
  arg2 = (double)jarg2; 
  if (arg1) (arg1)->temperatureInC = arg2;
}


SWIGEXPORT jdouble JNICALL Java_com_projectpluto_astro_astroJNI_FixedBrightnessData_1temperatureInC_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  FixedBrightnessData *arg1 = (FixedBrightnessData *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(FixedBrightnessData **)&jarg1; 
  result = (double) ((arg1)->temperatureInC);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_projectpluto_astro_astroJNI_FixedBrightnessData_1relativeHumidity_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  FixedBrightnessData *arg1 = (FixedBrightnessData *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(FixedBrightnessData **)&jarg1; 
  arg2 = (double)jarg2; 
  if (arg1) (arg1)->relativeHumidity = arg2;
}


SWIGEXPORT jdouble JNICALL Java_com_projectpluto_astro_astroJNI_FixedBrightnessData_1relativeHumidity_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  FixedBrightnessData *arg1 = (FixedBrightnessData *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(FixedBrightnessData **)&jarg1; 
  result = (double) ((arg1)->relativeHumidity);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_projectpluto_astro_astroJNI_FixedBrightnessData_1year_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  FixedBrightnessData *arg1 = (FixedBrightnessData *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(FixedBrightnessData **)&jarg1; 
  arg2 = (double)jarg2; 
  if (arg1) (arg1)->year = arg2;
}


SWIGEXPORT jdouble JNICALL Java_com_projectpluto_astro_astroJNI_FixedBrightnessData_1year_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  FixedBrightnessData *arg1 = (FixedBrightnessData *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(FixedBrightnessData **)&jarg1; 
  result = (double) ((arg1)->year);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_projectpluto_astro_astroJNI_FixedBrightnessData_1month_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  FixedBrightnessData *arg1 = (FixedBrightnessData *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(FixedBrightnessData **)&jarg1; 
  arg2 = (double)jarg2; 
  if (arg1) (arg1)->month = arg2;
}


SWIGEXPORT jdouble JNICALL Java_com_projectpluto_astro_astroJNI_FixedBrightnessData_1month_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  FixedBrightnessData *arg1 = (FixedBrightnessData *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(FixedBrightnessData **)&jarg1; 
  result = (double) ((arg1)->month);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_projectpluto_astro_astroJNI_new_1FixedBrightnessData(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  FixedBrightnessData *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (FixedBrightnessData *)new FixedBrightnessData();
  *(FixedBrightnessData **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_projectpluto_astro_astroJNI_delete_1FixedBrightnessData(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  FixedBrightnessData *arg1 = (FixedBrightnessData *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(FixedBrightnessData **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_com_projectpluto_astro_astroJNI_AngularBrightnessData_1zenithAngle_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  AngularBrightnessData *arg1 = (AngularBrightnessData *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(AngularBrightnessData **)&jarg1; 
  arg2 = (double)jarg2; 
  if (arg1) (arg1)->zenithAngle = arg2;
}


SWIGEXPORT jdouble JNICALL Java_com_projectpluto_astro_astroJNI_AngularBrightnessData_1zenithAngle_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  AngularBrightnessData *arg1 = (AngularBrightnessData *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(AngularBrightnessData **)&jarg1; 
  result = (double) ((arg1)->zenithAngle);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_projectpluto_astro_astroJNI_AngularBrightnessData_1distMoon_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  AngularBrightnessData *arg1 = (AngularBrightnessData *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(AngularBrightnessData **)&jarg1; 
  arg2 = (double)jarg2; 
  if (arg1) (arg1)->distMoon = arg2;
}


SWIGEXPORT jdouble JNICALL Java_com_projectpluto_astro_astroJNI_AngularBrightnessData_1distMoon_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  AngularBrightnessData *arg1 = (AngularBrightnessData *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(AngularBrightnessData **)&jarg1; 
  result = (double) ((arg1)->distMoon);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_projectpluto_astro_astroJNI_AngularBrightnessData_1distSun_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  AngularBrightnessData *arg1 = (AngularBrightnessData *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(AngularBrightnessData **)&jarg1; 
  arg2 = (double)jarg2; 
  if (arg1) (arg1)->distSun = arg2;
}


SWIGEXPORT jdouble JNICALL Java_com_projectpluto_astro_astroJNI_AngularBrightnessData_1distSun_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  AngularBrightnessData *arg1 = (AngularBrightnessData *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(AngularBrightnessData **)&jarg1; 
  result = (double) ((arg1)->distSun);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_projectpluto_astro_astroJNI_new_1AngularBrightnessData(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  AngularBrightnessData *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (AngularBrightnessData *)new AngularBrightnessData();
  *(AngularBrightnessData **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_projectpluto_astro_astroJNI_delete_1AngularBrightnessData(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  AngularBrightnessData *arg1 = (AngularBrightnessData *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(AngularBrightnessData **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jint JNICALL Java_com_projectpluto_astro_astroJNI_VisLimit_1setBrightnessParams(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jint jresult = 0 ;
  VisLimit *arg1 = (VisLimit *) 0 ;
  FixedBrightnessData *arg2 = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(VisLimit **)&jarg1; 
  arg2 = *(FixedBrightnessData **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "FixedBrightnessData & reference is null");
    return 0;
  } 
  result = (int)(arg1)->setBrightnessParams(*arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_projectpluto_astro_astroJNI_VisLimit_1computeSkyBrightness(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jint jresult = 0 ;
  VisLimit *arg1 = (VisLimit *) 0 ;
  AngularBrightnessData *arg2 = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(VisLimit **)&jarg1; 
  arg2 = *(AngularBrightnessData **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "AngularBrightnessData & reference is null");
    return 0;
  } 
  result = (int)(arg1)->computeSkyBrightness(*arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_com_projectpluto_astro_astroJNI_VisLimit_1computeLimitingMag(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  VisLimit *arg1 = (VisLimit *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(VisLimit **)&jarg1; 
  result = (double)(arg1)->computeLimitingMag();
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_projectpluto_astro_astroJNI_VisLimit_1computeExtinction(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  VisLimit *arg1 = (VisLimit *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(VisLimit **)&jarg1; 
  result = (int)(arg1)->computeExtinction();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_projectpluto_astro_astroJNI_VisLimit_1setMask(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  VisLimit *arg1 = (VisLimit *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(VisLimit **)&jarg1; 
  arg2 = (int)jarg2; 
  (arg1)->setMask(arg2);
}


SWIGEXPORT jdouble JNICALL Java_com_projectpluto_astro_astroJNI_VisLimit_1getK(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jdouble jresult = 0 ;
  VisLimit *arg1 = (VisLimit *) 0 ;
  unsigned int arg2 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(VisLimit **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  result = (double)(arg1)->getK(arg2);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_com_projectpluto_astro_astroJNI_VisLimit_1getBrightness(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jdouble jresult = 0 ;
  VisLimit *arg1 = (VisLimit *) 0 ;
  unsigned int arg2 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(VisLimit **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  result = (double)(arg1)->getBrightness(arg2);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_com_projectpluto_astro_astroJNI_VisLimit_1getExtinction(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jdouble jresult = 0 ;
  VisLimit *arg1 = (VisLimit *) 0 ;
  unsigned int arg2 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(VisLimit **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  result = (double)(arg1)->getExtinction(arg2);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_projectpluto_astro_astroJNI_new_1VisLimit(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  VisLimit *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (VisLimit *)new VisLimit();
  *(VisLimit **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_projectpluto_astro_astroJNI_delete_1VisLimit(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  VisLimit *arg1 = (VisLimit *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VisLimit **)&jarg1; 
  delete arg1;
}


#ifdef __cplusplus
}
#endif

