/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.naughter.aaplus;

public interface AAConstants {
  public final static String AAPLUS_VERSION = AAJNI.AAPLUS_VERSION_get();
  public final static int AAPLUS_VERSION_NUMBER = AAJNI.AAPLUS_VERSION_NUMBER_get();
}
