/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.naughter.aaplus;

public interface AAConstants {
    public final static int WINVER = AAJNI.WINVER_get();
    public final static int _WIN32_WINNT = AAJNI._WIN32_WINNT_get();
    public final static int _WIN32_WINDOWS = AAJNI._WIN32_WINDOWS_get();
    public final static int _WIN32_IE = AAJNI._WIN32_IE_get();
    public final static int _SECURE_ATL = AAJNI._SECURE_ATL_get();
}
