/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.naughter.aaplus;

public class CAA3DCoordinate {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CAA3DCoordinate(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CAA3DCoordinate obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CAA3DCoordinate obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AAJNI.delete_CAA3DCoordinate(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(double value) {
    AAJNI.CAA3DCoordinate_X_set(swigCPtr, this, value);
  }

  public double getX() {
    return AAJNI.CAA3DCoordinate_X_get(swigCPtr, this);
  }

  public void setY(double value) {
    AAJNI.CAA3DCoordinate_Y_set(swigCPtr, this, value);
  }

  public double getY() {
    return AAJNI.CAA3DCoordinate_Y_get(swigCPtr, this);
  }

  public void setZ(double value) {
    AAJNI.CAA3DCoordinate_Z_set(swigCPtr, this, value);
  }

  public double getZ() {
    return AAJNI.CAA3DCoordinate_Z_get(swigCPtr, this);
  }

  public CAA3DCoordinate() {
    this(AAJNI.new_CAA3DCoordinate(), true);
  }

}
