/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.naughter.aaplus;

public class CAAAberration {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CAAAberration(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CAAAberration obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AAJNI.delete_CAAAberration(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static CAA3DCoordinate EarthVelocity(double JD, boolean bHighPrecision) {
    return new CAA3DCoordinate(AAJNI.CAAAberration_EarthVelocity(JD, bHighPrecision), true);
  }

  public static CAA2DCoordinate EclipticAberration(double Alpha, double Delta, double JD, boolean bHighPrecision) {
    return new CAA2DCoordinate(AAJNI.CAAAberration_EclipticAberration(Alpha, Delta, JD, bHighPrecision), true);
  }

  public static CAA2DCoordinate EquatorialAberration(double Lambda, double Beta, double JD, boolean bHighPrecision) {
    return new CAA2DCoordinate(AAJNI.CAAAberration_EquatorialAberration(Lambda, Beta, JD, bHighPrecision), true);
  }

  public CAAAberration() {
    this(AAJNI.new_CAAAberration(), true);
  }

}
