/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.naughter.aaplus;

public class CAABinaryStarDetails {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CAABinaryStarDetails(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CAABinaryStarDetails obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AAJNI.delete_CAABinaryStarDetails(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CAABinaryStarDetails() {
    this(AAJNI.new_CAABinaryStarDetails__SWIG_0(), true);
  }

  public CAABinaryStarDetails(CAABinaryStarDetails arg0) {
    this(AAJNI.new_CAABinaryStarDetails__SWIG_1(CAABinaryStarDetails.getCPtr(arg0), arg0), true);
  }

  public void setR(double value) {
    AAJNI.CAABinaryStarDetails_r_set(swigCPtr, this, value);
  }

  public double getR() {
    return AAJNI.CAABinaryStarDetails_r_get(swigCPtr, this);
  }

  public void setTheta(double value) {
    AAJNI.CAABinaryStarDetails_Theta_set(swigCPtr, this, value);
  }

  public double getTheta() {
    return AAJNI.CAABinaryStarDetails_Theta_get(swigCPtr, this);
  }

  public void setRho(double value) {
    AAJNI.CAABinaryStarDetails_Rho_set(swigCPtr, this, value);
  }

  public double getRho() {
    return AAJNI.CAABinaryStarDetails_Rho_get(swigCPtr, this);
  }

}
