/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.naughter.aaplus;

public class CAADiameters {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CAADiameters(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CAADiameters obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AAJNI.delete_CAADiameters(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static double SunSemidiameterA(double Delta) {
    return AAJNI.CAADiameters_SunSemidiameterA(Delta);
  }

  public static double MercurySemidiameterA(double Delta) {
    return AAJNI.CAADiameters_MercurySemidiameterA(Delta);
  }

  public static double VenusSemidiameterA(double Delta) {
    return AAJNI.CAADiameters_VenusSemidiameterA(Delta);
  }

  public static double MarsSemidiameterA(double Delta) {
    return AAJNI.CAADiameters_MarsSemidiameterA(Delta);
  }

  public static double JupiterEquatorialSemidiameterA(double Delta) {
    return AAJNI.CAADiameters_JupiterEquatorialSemidiameterA(Delta);
  }

  public static double JupiterPolarSemidiameterA(double Delta) {
    return AAJNI.CAADiameters_JupiterPolarSemidiameterA(Delta);
  }

  public static double SaturnEquatorialSemidiameterA(double Delta) {
    return AAJNI.CAADiameters_SaturnEquatorialSemidiameterA(Delta);
  }

  public static double SaturnPolarSemidiameterA(double Delta) {
    return AAJNI.CAADiameters_SaturnPolarSemidiameterA(Delta);
  }

  public static double UranusSemidiameterA(double Delta) {
    return AAJNI.CAADiameters_UranusSemidiameterA(Delta);
  }

  public static double NeptuneSemidiameterA(double Delta) {
    return AAJNI.CAADiameters_NeptuneSemidiameterA(Delta);
  }

  public static double MercurySemidiameterB(double Delta) {
    return AAJNI.CAADiameters_MercurySemidiameterB(Delta);
  }

  public static double VenusSemidiameterB(double Delta) {
    return AAJNI.CAADiameters_VenusSemidiameterB(Delta);
  }

  public static double MarsSemidiameterB(double Delta) {
    return AAJNI.CAADiameters_MarsSemidiameterB(Delta);
  }

  public static double JupiterEquatorialSemidiameterB(double Delta) {
    return AAJNI.CAADiameters_JupiterEquatorialSemidiameterB(Delta);
  }

  public static double JupiterPolarSemidiameterB(double Delta) {
    return AAJNI.CAADiameters_JupiterPolarSemidiameterB(Delta);
  }

  public static double SaturnEquatorialSemidiameterB(double Delta) {
    return AAJNI.CAADiameters_SaturnEquatorialSemidiameterB(Delta);
  }

  public static double SaturnPolarSemidiameterB(double Delta) {
    return AAJNI.CAADiameters_SaturnPolarSemidiameterB(Delta);
  }

  public static double UranusSemidiameterB(double Delta) {
    return AAJNI.CAADiameters_UranusSemidiameterB(Delta);
  }

  public static double NeptuneSemidiameterB(double Delta) {
    return AAJNI.CAADiameters_NeptuneSemidiameterB(Delta);
  }

  public static double PlutoSemidiameterB(double Delta) {
    return AAJNI.CAADiameters_PlutoSemidiameterB(Delta);
  }

  public static double GeocentricMoonSemidiameter(double Delta) {
    return AAJNI.CAADiameters_GeocentricMoonSemidiameter(Delta);
  }

  public static double ApparentAsteroidDiameter(double Delta, double d) {
    return AAJNI.CAADiameters_ApparentAsteroidDiameter(Delta, d);
  }

  public static double ApparentSaturnPolarSemidiameterA(double Delta, double B) {
    return AAJNI.CAADiameters_ApparentSaturnPolarSemidiameterA(Delta, B);
  }

  public static double ApparentSaturnPolarSemidiameterB(double Delta, double B) {
    return AAJNI.CAADiameters_ApparentSaturnPolarSemidiameterB(Delta, B);
  }

  public static double TopocentricMoonSemidiameter(double DistanceDelta, double Delta, double H, double Latitude, double Height) {
    return AAJNI.CAADiameters_TopocentricMoonSemidiameter(DistanceDelta, Delta, H, Latitude, Height);
  }

  public static double AsteroidDiameter(double H, double A) {
    return AAJNI.CAADiameters_AsteroidDiameter(H, A);
  }

  public CAADiameters() {
    this(AAJNI.new_CAADiameters(), true);
  }

}
