/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.naughter.aaplus;

public class CAAEllipticalObjectElements {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CAAEllipticalObjectElements(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CAAEllipticalObjectElements obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AAJNI.delete_CAAEllipticalObjectElements(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CAAEllipticalObjectElements() {
    this(AAJNI.new_CAAEllipticalObjectElements__SWIG_0(), true);
  }

  public CAAEllipticalObjectElements(CAAEllipticalObjectElements arg0) {
    this(AAJNI.new_CAAEllipticalObjectElements__SWIG_1(CAAEllipticalObjectElements.getCPtr(arg0), arg0), true);
  }

  public void setA(double value) {
    AAJNI.CAAEllipticalObjectElements_a_set(swigCPtr, this, value);
  }

  public double getA() {
    return AAJNI.CAAEllipticalObjectElements_a_get(swigCPtr, this);
  }

  public void setE(double value) {
    AAJNI.CAAEllipticalObjectElements_e_set(swigCPtr, this, value);
  }

  public double getE() {
    return AAJNI.CAAEllipticalObjectElements_e_get(swigCPtr, this);
  }

  public void setI(double value) {
    AAJNI.CAAEllipticalObjectElements_i_set(swigCPtr, this, value);
  }

  public double getI() {
    return AAJNI.CAAEllipticalObjectElements_i_get(swigCPtr, this);
  }

  public void setW(double value) {
    AAJNI.CAAEllipticalObjectElements_w_set(swigCPtr, this, value);
  }

  public double getW() {
    return AAJNI.CAAEllipticalObjectElements_w_get(swigCPtr, this);
  }

  public void setOmega(double value) {
    AAJNI.CAAEllipticalObjectElements_omega_set(swigCPtr, this, value);
  }

  public double getOmega() {
    return AAJNI.CAAEllipticalObjectElements_omega_get(swigCPtr, this);
  }

  public void setJDEquinox(double value) {
    AAJNI.CAAEllipticalObjectElements_JDEquinox_set(swigCPtr, this, value);
  }

  public double getJDEquinox() {
    return AAJNI.CAAEllipticalObjectElements_JDEquinox_get(swigCPtr, this);
  }

  public void setT(double value) {
    AAJNI.CAAEllipticalObjectElements_T_set(swigCPtr, this, value);
  }

  public double getT() {
    return AAJNI.CAAEllipticalObjectElements_T_get(swigCPtr, this);
  }

}
