/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.naughter.aaplus;

public class CAAEllipticalObjectDetails {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CAAEllipticalObjectDetails(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CAAEllipticalObjectDetails obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AAJNI.delete_CAAEllipticalObjectDetails(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CAAEllipticalObjectDetails() {
    this(AAJNI.new_CAAEllipticalObjectDetails(), true);
  }

  public void setHeliocentricRectangularEquatorial(CAA3DCoordinate value) {
    AAJNI.CAAEllipticalObjectDetails_HeliocentricRectangularEquatorial_set(swigCPtr, this, CAA3DCoordinate.getCPtr(value), value);
  }

  public CAA3DCoordinate getHeliocentricRectangularEquatorial() {
    long cPtr = AAJNI.CAAEllipticalObjectDetails_HeliocentricRectangularEquatorial_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CAA3DCoordinate(cPtr, false);
  }

  public void setHeliocentricRectangularEcliptical(CAA3DCoordinate value) {
    AAJNI.CAAEllipticalObjectDetails_HeliocentricRectangularEcliptical_set(swigCPtr, this, CAA3DCoordinate.getCPtr(value), value);
  }

  public CAA3DCoordinate getHeliocentricRectangularEcliptical() {
    long cPtr = AAJNI.CAAEllipticalObjectDetails_HeliocentricRectangularEcliptical_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CAA3DCoordinate(cPtr, false);
  }

  public void setHeliocentricEclipticLongitude(double value) {
    AAJNI.CAAEllipticalObjectDetails_HeliocentricEclipticLongitude_set(swigCPtr, this, value);
  }

  public double getHeliocentricEclipticLongitude() {
    return AAJNI.CAAEllipticalObjectDetails_HeliocentricEclipticLongitude_get(swigCPtr, this);
  }

  public void setHeliocentricEclipticLatitude(double value) {
    AAJNI.CAAEllipticalObjectDetails_HeliocentricEclipticLatitude_set(swigCPtr, this, value);
  }

  public double getHeliocentricEclipticLatitude() {
    return AAJNI.CAAEllipticalObjectDetails_HeliocentricEclipticLatitude_get(swigCPtr, this);
  }

  public void setTrueGeocentricRA(double value) {
    AAJNI.CAAEllipticalObjectDetails_TrueGeocentricRA_set(swigCPtr, this, value);
  }

  public double getTrueGeocentricRA() {
    return AAJNI.CAAEllipticalObjectDetails_TrueGeocentricRA_get(swigCPtr, this);
  }

  public void setTrueGeocentricDeclination(double value) {
    AAJNI.CAAEllipticalObjectDetails_TrueGeocentricDeclination_set(swigCPtr, this, value);
  }

  public double getTrueGeocentricDeclination() {
    return AAJNI.CAAEllipticalObjectDetails_TrueGeocentricDeclination_get(swigCPtr, this);
  }

  public void setTrueGeocentricDistance(double value) {
    AAJNI.CAAEllipticalObjectDetails_TrueGeocentricDistance_set(swigCPtr, this, value);
  }

  public double getTrueGeocentricDistance() {
    return AAJNI.CAAEllipticalObjectDetails_TrueGeocentricDistance_get(swigCPtr, this);
  }

  public void setTrueGeocentricLightTime(double value) {
    AAJNI.CAAEllipticalObjectDetails_TrueGeocentricLightTime_set(swigCPtr, this, value);
  }

  public double getTrueGeocentricLightTime() {
    return AAJNI.CAAEllipticalObjectDetails_TrueGeocentricLightTime_get(swigCPtr, this);
  }

  public void setAstrometricGeocentricRA(double value) {
    AAJNI.CAAEllipticalObjectDetails_AstrometricGeocentricRA_set(swigCPtr, this, value);
  }

  public double getAstrometricGeocentricRA() {
    return AAJNI.CAAEllipticalObjectDetails_AstrometricGeocentricRA_get(swigCPtr, this);
  }

  public void setAstrometricGeocentricDeclination(double value) {
    AAJNI.CAAEllipticalObjectDetails_AstrometricGeocentricDeclination_set(swigCPtr, this, value);
  }

  public double getAstrometricGeocentricDeclination() {
    return AAJNI.CAAEllipticalObjectDetails_AstrometricGeocentricDeclination_get(swigCPtr, this);
  }

  public void setAstrometricGeocentricDistance(double value) {
    AAJNI.CAAEllipticalObjectDetails_AstrometricGeocentricDistance_set(swigCPtr, this, value);
  }

  public double getAstrometricGeocentricDistance() {
    return AAJNI.CAAEllipticalObjectDetails_AstrometricGeocentricDistance_get(swigCPtr, this);
  }

  public void setAstrometricGeocentricLightTime(double value) {
    AAJNI.CAAEllipticalObjectDetails_AstrometricGeocentricLightTime_set(swigCPtr, this, value);
  }

  public double getAstrometricGeocentricLightTime() {
    return AAJNI.CAAEllipticalObjectDetails_AstrometricGeocentricLightTime_get(swigCPtr, this);
  }

  public void setElongation(double value) {
    AAJNI.CAAEllipticalObjectDetails_Elongation_set(swigCPtr, this, value);
  }

  public double getElongation() {
    return AAJNI.CAAEllipticalObjectDetails_Elongation_get(swigCPtr, this);
  }

  public void setPhaseAngle(double value) {
    AAJNI.CAAEllipticalObjectDetails_PhaseAngle_set(swigCPtr, this, value);
  }

  public double getPhaseAngle() {
    return AAJNI.CAAEllipticalObjectDetails_PhaseAngle_get(swigCPtr, this);
  }

}
