/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.naughter.aaplus;

public class CAAEllipticalPlanetaryDetails {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CAAEllipticalPlanetaryDetails(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CAAEllipticalPlanetaryDetails obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CAAEllipticalPlanetaryDetails obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AAJNI.delete_CAAEllipticalPlanetaryDetails(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setApparentGeocentricEclipticalLongitude(double value) {
    AAJNI.CAAEllipticalPlanetaryDetails_ApparentGeocentricEclipticalLongitude_set(swigCPtr, this, value);
  }

  public double getApparentGeocentricEclipticalLongitude() {
    return AAJNI.CAAEllipticalPlanetaryDetails_ApparentGeocentricEclipticalLongitude_get(swigCPtr, this);
  }

  public void setApparentGeocentricEclipticalLatitude(double value) {
    AAJNI.CAAEllipticalPlanetaryDetails_ApparentGeocentricEclipticalLatitude_set(swigCPtr, this, value);
  }

  public double getApparentGeocentricEclipticalLatitude() {
    return AAJNI.CAAEllipticalPlanetaryDetails_ApparentGeocentricEclipticalLatitude_get(swigCPtr, this);
  }

  public void setApparentGeocentricDistance(double value) {
    AAJNI.CAAEllipticalPlanetaryDetails_ApparentGeocentricDistance_set(swigCPtr, this, value);
  }

  public double getApparentGeocentricDistance() {
    return AAJNI.CAAEllipticalPlanetaryDetails_ApparentGeocentricDistance_get(swigCPtr, this);
  }

  public void setApparentLightTime(double value) {
    AAJNI.CAAEllipticalPlanetaryDetails_ApparentLightTime_set(swigCPtr, this, value);
  }

  public double getApparentLightTime() {
    return AAJNI.CAAEllipticalPlanetaryDetails_ApparentLightTime_get(swigCPtr, this);
  }

  public void setApparentGeocentricRA(double value) {
    AAJNI.CAAEllipticalPlanetaryDetails_ApparentGeocentricRA_set(swigCPtr, this, value);
  }

  public double getApparentGeocentricRA() {
    return AAJNI.CAAEllipticalPlanetaryDetails_ApparentGeocentricRA_get(swigCPtr, this);
  }

  public void setApparentGeocentricDeclination(double value) {
    AAJNI.CAAEllipticalPlanetaryDetails_ApparentGeocentricDeclination_set(swigCPtr, this, value);
  }

  public double getApparentGeocentricDeclination() {
    return AAJNI.CAAEllipticalPlanetaryDetails_ApparentGeocentricDeclination_get(swigCPtr, this);
  }

  public void setTrueGeocentricRectangularEcliptical(CAA3DCoordinate value) {
    AAJNI.CAAEllipticalPlanetaryDetails_TrueGeocentricRectangularEcliptical_set(swigCPtr, this, CAA3DCoordinate.getCPtr(value), value);
  }

  public CAA3DCoordinate getTrueGeocentricRectangularEcliptical() {
    long cPtr = AAJNI.CAAEllipticalPlanetaryDetails_TrueGeocentricRectangularEcliptical_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CAA3DCoordinate(cPtr, false);
  }

  public void setTrueHeliocentricEclipticalLongitude(double value) {
    AAJNI.CAAEllipticalPlanetaryDetails_TrueHeliocentricEclipticalLongitude_set(swigCPtr, this, value);
  }

  public double getTrueHeliocentricEclipticalLongitude() {
    return AAJNI.CAAEllipticalPlanetaryDetails_TrueHeliocentricEclipticalLongitude_get(swigCPtr, this);
  }

  public void setTrueHeliocentricEclipticalLatitude(double value) {
    AAJNI.CAAEllipticalPlanetaryDetails_TrueHeliocentricEclipticalLatitude_set(swigCPtr, this, value);
  }

  public double getTrueHeliocentricEclipticalLatitude() {
    return AAJNI.CAAEllipticalPlanetaryDetails_TrueHeliocentricEclipticalLatitude_get(swigCPtr, this);
  }

  public void setTrueHeliocentricDistance(double value) {
    AAJNI.CAAEllipticalPlanetaryDetails_TrueHeliocentricDistance_set(swigCPtr, this, value);
  }

  public double getTrueHeliocentricDistance() {
    return AAJNI.CAAEllipticalPlanetaryDetails_TrueHeliocentricDistance_get(swigCPtr, this);
  }

  public void setTrueGeocentricEclipticalLongitude(double value) {
    AAJNI.CAAEllipticalPlanetaryDetails_TrueGeocentricEclipticalLongitude_set(swigCPtr, this, value);
  }

  public double getTrueGeocentricEclipticalLongitude() {
    return AAJNI.CAAEllipticalPlanetaryDetails_TrueGeocentricEclipticalLongitude_get(swigCPtr, this);
  }

  public void setTrueGeocentricEclipticalLatitude(double value) {
    AAJNI.CAAEllipticalPlanetaryDetails_TrueGeocentricEclipticalLatitude_set(swigCPtr, this, value);
  }

  public double getTrueGeocentricEclipticalLatitude() {
    return AAJNI.CAAEllipticalPlanetaryDetails_TrueGeocentricEclipticalLatitude_get(swigCPtr, this);
  }

  public void setTrueGeocentricDistance(double value) {
    AAJNI.CAAEllipticalPlanetaryDetails_TrueGeocentricDistance_set(swigCPtr, this, value);
  }

  public double getTrueGeocentricDistance() {
    return AAJNI.CAAEllipticalPlanetaryDetails_TrueGeocentricDistance_get(swigCPtr, this);
  }

  public void setTrueLightTime(double value) {
    AAJNI.CAAEllipticalPlanetaryDetails_TrueLightTime_set(swigCPtr, this, value);
  }

  public double getTrueLightTime() {
    return AAJNI.CAAEllipticalPlanetaryDetails_TrueLightTime_get(swigCPtr, this);
  }

  public void setTrueGeocentricRA(double value) {
    AAJNI.CAAEllipticalPlanetaryDetails_TrueGeocentricRA_set(swigCPtr, this, value);
  }

  public double getTrueGeocentricRA() {
    return AAJNI.CAAEllipticalPlanetaryDetails_TrueGeocentricRA_get(swigCPtr, this);
  }

  public void setTrueGeocentricDeclination(double value) {
    AAJNI.CAAEllipticalPlanetaryDetails_TrueGeocentricDeclination_set(swigCPtr, this, value);
  }

  public double getTrueGeocentricDeclination() {
    return AAJNI.CAAEllipticalPlanetaryDetails_TrueGeocentricDeclination_get(swigCPtr, this);
  }

  public CAAEllipticalPlanetaryDetails() {
    this(AAJNI.new_CAAEllipticalPlanetaryDetails(), true);
  }

}
