/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.naughter.aaplus;

public class CAAEclipses {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CAAEclipses(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CAAEclipses obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AAJNI.delete_CAAEclipses(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static CAASolarEclipseDetails CalculateSolar(double k) {
    return new CAASolarEclipseDetails(AAJNI.CAAEclipses_CalculateSolar(k), true);
  }

  public static CAALunarEclipseDetails CalculateLunar(double k) {
    return new CAALunarEclipseDetails(AAJNI.CAAEclipses_CalculateLunar(k), true);
  }

  public CAAEclipses() {
    this(AAJNI.new_CAAEclipses(), true);
  }

}
