/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.naughter.aaplus;

public class CAAEarth {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CAAEarth(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CAAEarth obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AAJNI.delete_CAAEarth(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static double EclipticLongitude(double JD, boolean bHighPrecision) {
    return AAJNI.CAAEarth_EclipticLongitude(JD, bHighPrecision);
  }

  public static double EclipticLatitude(double JD, boolean bHighPrecision) {
    return AAJNI.CAAEarth_EclipticLatitude(JD, bHighPrecision);
  }

  public static double RadiusVector(double JD, boolean bHighPrecision) {
    return AAJNI.CAAEarth_RadiusVector(JD, bHighPrecision);
  }

  public static double SunMeanAnomaly(double JD) {
    return AAJNI.CAAEarth_SunMeanAnomaly(JD);
  }

  public static double Eccentricity(double JD) {
    return AAJNI.CAAEarth_Eccentricity(JD);
  }

  public static double EclipticLongitudeJ2000(double JD, boolean bHighPrecision) {
    return AAJNI.CAAEarth_EclipticLongitudeJ2000(JD, bHighPrecision);
  }

  public static double EclipticLatitudeJ2000(double JD, boolean bHighPrecision) {
    return AAJNI.CAAEarth_EclipticLatitudeJ2000(JD, bHighPrecision);
  }

  public CAAEarth() {
    this(AAJNI.new_CAAEarth(), true);
  }

}
