/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.naughter.aaplus;

public class CAAFK5 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CAAFK5(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CAAFK5 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CAAFK5 obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AAJNI.delete_CAAFK5(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static double CorrectionInLongitude(double Longitude, double Latitude, double JD) {
    return AAJNI.CAAFK5_CorrectionInLongitude(Longitude, Latitude, JD);
  }

  public static double CorrectionInLatitude(double Longitude, double JD) {
    return AAJNI.CAAFK5_CorrectionInLatitude(Longitude, JD);
  }

  public static CAA3DCoordinate ConvertVSOPToFK5J2000(CAA3DCoordinate value) {
    return new CAA3DCoordinate(AAJNI.CAAFK5_ConvertVSOPToFK5J2000(CAA3DCoordinate.getCPtr(value), value), true);
  }

  public static CAA3DCoordinate ConvertVSOPToFK5B1950(CAA3DCoordinate value) {
    return new CAA3DCoordinate(AAJNI.CAAFK5_ConvertVSOPToFK5B1950(CAA3DCoordinate.getCPtr(value), value), true);
  }

  public static CAA3DCoordinate ConvertVSOPToFK5AnyEquinox(CAA3DCoordinate value, double JDEquinox) {
    return new CAA3DCoordinate(AAJNI.CAAFK5_ConvertVSOPToFK5AnyEquinox(CAA3DCoordinate.getCPtr(value), value, JDEquinox), true);
  }

  public CAAFK5() {
    this(AAJNI.new_CAAFK5(), true);
  }

}
