/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.naughter.aaplus;

public class CAAKepler {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CAAKepler(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CAAKepler obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AAJNI.delete_CAAKepler(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static double Calculate(double M, double e, int nIterations) {
    return AAJNI.CAAKepler_Calculate__SWIG_0(M, e, nIterations);
  }

  public static double Calculate(double M, double e) {
    return AAJNI.CAAKepler_Calculate__SWIG_1(M, e);
  }

  public CAAKepler() {
    this(AAJNI.new_CAAKepler(), true);
  }

}
