/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.naughter.aaplus;

public class CAALunarEclipseDetails {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CAALunarEclipseDetails(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CAALunarEclipseDetails obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AAJNI.delete_CAALunarEclipseDetails(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CAALunarEclipseDetails() {
    this(AAJNI.new_CAALunarEclipseDetails__SWIG_0(), true);
  }

  public CAALunarEclipseDetails(CAALunarEclipseDetails arg0) {
    this(AAJNI.new_CAALunarEclipseDetails__SWIG_1(CAALunarEclipseDetails.getCPtr(arg0), arg0), true);
  }

  public void setBEclipse(boolean value) {
    AAJNI.CAALunarEclipseDetails_bEclipse_set(swigCPtr, this, value);
  }

  public boolean getBEclipse() {
    return AAJNI.CAALunarEclipseDetails_bEclipse_get(swigCPtr, this);
  }

  public void setTimeOfMaximumEclipse(double value) {
    AAJNI.CAALunarEclipseDetails_TimeOfMaximumEclipse_set(swigCPtr, this, value);
  }

  public double getTimeOfMaximumEclipse() {
    return AAJNI.CAALunarEclipseDetails_TimeOfMaximumEclipse_get(swigCPtr, this);
  }

  public void setF(double value) {
    AAJNI.CAALunarEclipseDetails_F_set(swigCPtr, this, value);
  }

  public double getF() {
    return AAJNI.CAALunarEclipseDetails_F_get(swigCPtr, this);
  }

  public void setU(double value) {
    AAJNI.CAALunarEclipseDetails_u_set(swigCPtr, this, value);
  }

  public double getU() {
    return AAJNI.CAALunarEclipseDetails_u_get(swigCPtr, this);
  }

  public void setGamma(double value) {
    AAJNI.CAALunarEclipseDetails_gamma_set(swigCPtr, this, value);
  }

  public double getGamma() {
    return AAJNI.CAALunarEclipseDetails_gamma_get(swigCPtr, this);
  }

  public void setPenumbralRadii(double value) {
    AAJNI.CAALunarEclipseDetails_PenumbralRadii_set(swigCPtr, this, value);
  }

  public double getPenumbralRadii() {
    return AAJNI.CAALunarEclipseDetails_PenumbralRadii_get(swigCPtr, this);
  }

  public void setUmbralRadii(double value) {
    AAJNI.CAALunarEclipseDetails_UmbralRadii_set(swigCPtr, this, value);
  }

  public double getUmbralRadii() {
    return AAJNI.CAALunarEclipseDetails_UmbralRadii_get(swigCPtr, this);
  }

  public void setPenumbralMagnitude(double value) {
    AAJNI.CAALunarEclipseDetails_PenumbralMagnitude_set(swigCPtr, this, value);
  }

  public double getPenumbralMagnitude() {
    return AAJNI.CAALunarEclipseDetails_PenumbralMagnitude_get(swigCPtr, this);
  }

  public void setUmbralMagnitude(double value) {
    AAJNI.CAALunarEclipseDetails_UmbralMagnitude_set(swigCPtr, this, value);
  }

  public double getUmbralMagnitude() {
    return AAJNI.CAALunarEclipseDetails_UmbralMagnitude_get(swigCPtr, this);
  }

  public void setPartialPhaseSemiDuration(double value) {
    AAJNI.CAALunarEclipseDetails_PartialPhaseSemiDuration_set(swigCPtr, this, value);
  }

  public double getPartialPhaseSemiDuration() {
    return AAJNI.CAALunarEclipseDetails_PartialPhaseSemiDuration_get(swigCPtr, this);
  }

  public void setTotalPhaseSemiDuration(double value) {
    AAJNI.CAALunarEclipseDetails_TotalPhaseSemiDuration_set(swigCPtr, this, value);
  }

  public double getTotalPhaseSemiDuration() {
    return AAJNI.CAALunarEclipseDetails_TotalPhaseSemiDuration_get(swigCPtr, this);
  }

  public void setPartialPhasePenumbraSemiDuration(double value) {
    AAJNI.CAALunarEclipseDetails_PartialPhasePenumbraSemiDuration_set(swigCPtr, this, value);
  }

  public double getPartialPhasePenumbraSemiDuration() {
    return AAJNI.CAALunarEclipseDetails_PartialPhasePenumbraSemiDuration_get(swigCPtr, this);
  }

}
