/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.naughter.aaplus;

public class CAAMoonIlluminatedFraction {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CAAMoonIlluminatedFraction(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CAAMoonIlluminatedFraction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CAAMoonIlluminatedFraction obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AAJNI.delete_CAAMoonIlluminatedFraction(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static double GeocentricElongation(double ObjectAlpha, double ObjectDelta, double SunAlpha, double SunDelta) {
    return AAJNI.CAAMoonIlluminatedFraction_GeocentricElongation(ObjectAlpha, ObjectDelta, SunAlpha, SunDelta);
  }

  public static double PhaseAngle(double GeocentricElongation, double EarthObjectDistance, double EarthSunDistance) {
    return AAJNI.CAAMoonIlluminatedFraction_PhaseAngle(GeocentricElongation, EarthObjectDistance, EarthSunDistance);
  }

  public static double IlluminatedFraction(double PhaseAngle) {
    return AAJNI.CAAMoonIlluminatedFraction_IlluminatedFraction(PhaseAngle);
  }

  public static double PositionAngle(double Alpha0, double Delta0, double Alpha, double Delta) {
    return AAJNI.CAAMoonIlluminatedFraction_PositionAngle(Alpha0, Delta0, Alpha, Delta);
  }

  public CAAMoonIlluminatedFraction() {
    this(AAJNI.new_CAAMoonIlluminatedFraction(), true);
  }

}
