/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.naughter.aaplus;

public class CAANearParabolicObjectElements {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CAANearParabolicObjectElements(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CAANearParabolicObjectElements obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AAJNI.delete_CAANearParabolicObjectElements(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CAANearParabolicObjectElements() {
    this(AAJNI.new_CAANearParabolicObjectElements__SWIG_0(), true);
  }

  public CAANearParabolicObjectElements(CAANearParabolicObjectElements arg0) {
    this(AAJNI.new_CAANearParabolicObjectElements__SWIG_1(CAANearParabolicObjectElements.getCPtr(arg0), arg0), true);
  }

  public void setQ(double value) {
    AAJNI.CAANearParabolicObjectElements_q_set(swigCPtr, this, value);
  }

  public double getQ() {
    return AAJNI.CAANearParabolicObjectElements_q_get(swigCPtr, this);
  }

  public void setI(double value) {
    AAJNI.CAANearParabolicObjectElements_i_set(swigCPtr, this, value);
  }

  public double getI() {
    return AAJNI.CAANearParabolicObjectElements_i_get(swigCPtr, this);
  }

  public void setW(double value) {
    AAJNI.CAANearParabolicObjectElements_w_set(swigCPtr, this, value);
  }

  public double getW() {
    return AAJNI.CAANearParabolicObjectElements_w_get(swigCPtr, this);
  }

  public void setOmega(double value) {
    AAJNI.CAANearParabolicObjectElements_omega_set(swigCPtr, this, value);
  }

  public double getOmega() {
    return AAJNI.CAANearParabolicObjectElements_omega_get(swigCPtr, this);
  }

  public void setJDEquinox(double value) {
    AAJNI.CAANearParabolicObjectElements_JDEquinox_set(swigCPtr, this, value);
  }

  public double getJDEquinox() {
    return AAJNI.CAANearParabolicObjectElements_JDEquinox_get(swigCPtr, this);
  }

  public void setT(double value) {
    AAJNI.CAANearParabolicObjectElements_T_set(swigCPtr, this, value);
  }

  public double getT() {
    return AAJNI.CAANearParabolicObjectElements_T_get(swigCPtr, this);
  }

  public void setE(double value) {
    AAJNI.CAANearParabolicObjectElements_e_set(swigCPtr, this, value);
  }

  public double getE() {
    return AAJNI.CAANearParabolicObjectElements_e_get(swigCPtr, this);
  }

}
