/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.naughter.aaplus;

public class CAANodes {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CAANodes(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CAANodes obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CAANodes obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AAJNI.delete_CAANodes(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static CAANodeObjectDetails PassageThroAscendingNode(CAAEllipticalObjectElements elements) {
    return new CAANodeObjectDetails(AAJNI.CAANodes_PassageThroAscendingNode__SWIG_0(CAAEllipticalObjectElements.getCPtr(elements), elements), true);
  }

  public static CAANodeObjectDetails PassageThroDescendingNode(CAAEllipticalObjectElements elements) {
    return new CAANodeObjectDetails(AAJNI.CAANodes_PassageThroDescendingNode__SWIG_0(CAAEllipticalObjectElements.getCPtr(elements), elements), true);
  }

  public static CAANodeObjectDetails PassageThroAscendingNode(CAAParabolicObjectElements elements) {
    return new CAANodeObjectDetails(AAJNI.CAANodes_PassageThroAscendingNode__SWIG_1(CAAParabolicObjectElements.getCPtr(elements), elements), true);
  }

  public static CAANodeObjectDetails PassageThroDescendingNode(CAAParabolicObjectElements elements) {
    return new CAANodeObjectDetails(AAJNI.CAANodes_PassageThroDescendingNode__SWIG_1(CAAParabolicObjectElements.getCPtr(elements), elements), true);
  }

  public CAANodes() {
    this(AAJNI.new_CAANodes(), true);
  }

}
