/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.naughter.aaplus;

public class CAANodes {
    private long swigCPtr;
    protected boolean swigCMemOwn;

    protected CAANodes(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }

    protected static long getCPtr(CAANodes obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                AAJNI.delete_CAANodes(swigCPtr);
            }
            swigCPtr = 0;
        }
    }

    public static CAANodeObjectDetails PassageThroAscendingNode(CAAEllipticalObjectElements elements) {
        return new CAANodeObjectDetails(AAJNI.CAANodes_PassageThroAscendingNode__SWIG_0(CAAEllipticalObjectElements.getCPtr(elements), elements), true);
    }

    public static CAANodeObjectDetails PassageThroDescendingNode(CAAEllipticalObjectElements elements) {
        return new CAANodeObjectDetails(AAJNI.CAANodes_PassageThroDescendingNode__SWIG_0(CAAEllipticalObjectElements.getCPtr(elements), elements), true);
    }

    public static CAANodeObjectDetails PassageThroAscendingNode(CAAParabolicObjectElements elements) {
        return new CAANodeObjectDetails(AAJNI.CAANodes_PassageThroAscendingNode__SWIG_1(CAAParabolicObjectElements.getCPtr(elements), elements), true);
    }

    public static CAANodeObjectDetails PassageThroDescendingNode(CAAParabolicObjectElements elements) {
        return new CAANodeObjectDetails(AAJNI.CAANodes_PassageThroDescendingNode__SWIG_1(CAAParabolicObjectElements.getCPtr(elements), elements), true);
    }

    public CAANodes() {
        this(AAJNI.new_CAANodes(), true);
    }

}
