/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.naughter.aaplus;

public class CAAPlanetPerihelionAphelion {
    private long swigCPtr;
    protected boolean swigCMemOwn;

    protected CAAPlanetPerihelionAphelion(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }

    protected static long getCPtr(CAAPlanetPerihelionAphelion obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                AAJNI.delete_CAAPlanetPerihelionAphelion(swigCPtr);
            }
            swigCPtr = 0;
        }
    }

    public static int MercuryK(double Year) {
        return AAJNI.CAAPlanetPerihelionAphelion_MercuryK(Year);
    }

    public static double MercuryPerihelion(int k) {
        return AAJNI.CAAPlanetPerihelionAphelion_MercuryPerihelion(k);
    }

    public static double MercuryAphelion(int k) {
        return AAJNI.CAAPlanetPerihelionAphelion_MercuryAphelion(k);
    }

    public static int VenusK(double Year) {
        return AAJNI.CAAPlanetPerihelionAphelion_VenusK(Year);
    }

    public static double VenusPerihelion(int k) {
        return AAJNI.CAAPlanetPerihelionAphelion_VenusPerihelion(k);
    }

    public static double VenusAphelion(int k) {
        return AAJNI.CAAPlanetPerihelionAphelion_VenusAphelion(k);
    }

    public static int EarthK(double Year) {
        return AAJNI.CAAPlanetPerihelionAphelion_EarthK(Year);
    }

    public static double EarthPerihelion(int k, boolean bBarycentric) {
        return AAJNI.CAAPlanetPerihelionAphelion_EarthPerihelion__SWIG_0(k, bBarycentric);
    }

    public static double EarthPerihelion(int k) {
        return AAJNI.CAAPlanetPerihelionAphelion_EarthPerihelion__SWIG_1(k);
    }

    public static double EarthAphelion(int k, boolean bBarycentric) {
        return AAJNI.CAAPlanetPerihelionAphelion_EarthAphelion__SWIG_0(k, bBarycentric);
    }

    public static double EarthAphelion(int k) {
        return AAJNI.CAAPlanetPerihelionAphelion_EarthAphelion__SWIG_1(k);
    }

    public static int MarsK(double Year) {
        return AAJNI.CAAPlanetPerihelionAphelion_MarsK(Year);
    }

    public static double MarsPerihelion(int k) {
        return AAJNI.CAAPlanetPerihelionAphelion_MarsPerihelion(k);
    }

    public static double MarsAphelion(int k) {
        return AAJNI.CAAPlanetPerihelionAphelion_MarsAphelion(k);
    }

    public static int JupiterK(double Year) {
        return AAJNI.CAAPlanetPerihelionAphelion_JupiterK(Year);
    }

    public static double JupiterPerihelion(int k) {
        return AAJNI.CAAPlanetPerihelionAphelion_JupiterPerihelion(k);
    }

    public static double JupiterAphelion(int k) {
        return AAJNI.CAAPlanetPerihelionAphelion_JupiterAphelion(k);
    }

    public static int SaturnK(double Year) {
        return AAJNI.CAAPlanetPerihelionAphelion_SaturnK(Year);
    }

    public static double SaturnPerihelion(int k) {
        return AAJNI.CAAPlanetPerihelionAphelion_SaturnPerihelion(k);
    }

    public static double SaturnAphelion(int k) {
        return AAJNI.CAAPlanetPerihelionAphelion_SaturnAphelion(k);
    }

    public static int UranusK(double Year) {
        return AAJNI.CAAPlanetPerihelionAphelion_UranusK(Year);
    }

    public static double UranusPerihelion(int k) {
        return AAJNI.CAAPlanetPerihelionAphelion_UranusPerihelion(k);
    }

    public static double UranusAphelion(int k) {
        return AAJNI.CAAPlanetPerihelionAphelion_UranusAphelion(k);
    }

    public static int NeptuneK(double Year) {
        return AAJNI.CAAPlanetPerihelionAphelion_NeptuneK(Year);
    }

    public static double NeptunePerihelion(int k) {
        return AAJNI.CAAPlanetPerihelionAphelion_NeptunePerihelion(k);
    }

    public static double NeptuneAphelion(int k) {
        return AAJNI.CAAPlanetPerihelionAphelion_NeptuneAphelion(k);
    }

    public CAAPlanetPerihelionAphelion() {
        this(AAJNI.new_CAAPlanetPerihelionAphelion(), true);
    }

}
