/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.naughter.aaplus;

public class CAAPhysicalSun {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CAAPhysicalSun(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CAAPhysicalSun obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AAJNI.delete_CAAPhysicalSun(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static CAAPhysicalSunDetails Calculate(double JD, boolean bHighPrecision) {
    return new CAAPhysicalSunDetails(AAJNI.CAAPhysicalSun_Calculate(JD, bHighPrecision), true);
  }

  public static double TimeOfStartOfRotation(int C) {
    return AAJNI.CAAPhysicalSun_TimeOfStartOfRotation(C);
  }

  public CAAPhysicalSun() {
    this(AAJNI.new_CAAPhysicalSun(), true);
  }

}
