/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.naughter.aaplus;

public class CAAParabolic {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CAAParabolic(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CAAParabolic obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CAAParabolic obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AAJNI.delete_CAAParabolic(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static double CalculateBarkers(double W, double epsilon) {
    return AAJNI.CAAParabolic_CalculateBarkers__SWIG_0(W, epsilon);
  }

  public static double CalculateBarkers(double W) {
    return AAJNI.CAAParabolic_CalculateBarkers__SWIG_1(W);
  }

  public static CAAParabolicObjectDetails Calculate(double JD, CAAParabolicObjectElements elements, boolean bHighPrecision, double epsilon) {
    return new CAAParabolicObjectDetails(AAJNI.CAAParabolic_Calculate__SWIG_0(JD, CAAParabolicObjectElements.getCPtr(elements), elements, bHighPrecision, epsilon), true);
  }

  public static CAAParabolicObjectDetails Calculate(double JD, CAAParabolicObjectElements elements, boolean bHighPrecision) {
    return new CAAParabolicObjectDetails(AAJNI.CAAParabolic_Calculate__SWIG_1(JD, CAAParabolicObjectElements.getCPtr(elements), elements, bHighPrecision), true);
  }

  public CAAParabolic() {
    this(AAJNI.new_CAAParabolic(), true);
  }

}
