/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.naughter.aaplus;

public class CAAPhysicalMarsDetails {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CAAPhysicalMarsDetails(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CAAPhysicalMarsDetails obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AAJNI.delete_CAAPhysicalMarsDetails(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CAAPhysicalMarsDetails() {
    this(AAJNI.new_CAAPhysicalMarsDetails__SWIG_0(), true);
  }

  public CAAPhysicalMarsDetails(CAAPhysicalMarsDetails arg0) {
    this(AAJNI.new_CAAPhysicalMarsDetails__SWIG_1(CAAPhysicalMarsDetails.getCPtr(arg0), arg0), true);
  }

  public void setDE(double value) {
    AAJNI.CAAPhysicalMarsDetails_DE_set(swigCPtr, this, value);
  }

  public double getDE() {
    return AAJNI.CAAPhysicalMarsDetails_DE_get(swigCPtr, this);
  }

  public void setDS(double value) {
    AAJNI.CAAPhysicalMarsDetails_DS_set(swigCPtr, this, value);
  }

  public double getDS() {
    return AAJNI.CAAPhysicalMarsDetails_DS_get(swigCPtr, this);
  }

  public void setW(double value) {
    AAJNI.CAAPhysicalMarsDetails_w_set(swigCPtr, this, value);
  }

  public double getW() {
    return AAJNI.CAAPhysicalMarsDetails_w_get(swigCPtr, this);
  }

  public void setP(double value) {
    AAJNI.CAAPhysicalMarsDetails_P_set(swigCPtr, this, value);
  }

  public double getP() {
    return AAJNI.CAAPhysicalMarsDetails_P_get(swigCPtr, this);
  }

  public void setX(double value) {
    AAJNI.CAAPhysicalMarsDetails_X_set(swigCPtr, this, value);
  }

  public double getX() {
    return AAJNI.CAAPhysicalMarsDetails_X_get(swigCPtr, this);
  }

  public void setK(double value) {
    AAJNI.CAAPhysicalMarsDetails_k_set(swigCPtr, this, value);
  }

  public double getK() {
    return AAJNI.CAAPhysicalMarsDetails_k_get(swigCPtr, this);
  }

  public void setQ(double value) {
    AAJNI.CAAPhysicalMarsDetails_q_set(swigCPtr, this, value);
  }

  public double getQ() {
    return AAJNI.CAAPhysicalMarsDetails_q_get(swigCPtr, this);
  }

  public void setD(double value) {
    AAJNI.CAAPhysicalMarsDetails_d_set(swigCPtr, this, value);
  }

  public double getD() {
    return AAJNI.CAAPhysicalMarsDetails_d_get(swigCPtr, this);
  }

}
