/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.naughter.aaplus;

public class CAAPlanetPerihelionAphelion {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CAAPlanetPerihelionAphelion(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CAAPlanetPerihelionAphelion obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AAJNI.delete_CAAPlanetPerihelionAphelion(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static double MercuryK(double Year) {
    return AAJNI.CAAPlanetPerihelionAphelion_MercuryK(Year);
  }

  public static double Mercury(double k) {
    return AAJNI.CAAPlanetPerihelionAphelion_Mercury(k);
  }

  public static double VenusK(double Year) {
    return AAJNI.CAAPlanetPerihelionAphelion_VenusK(Year);
  }

  public static double Venus(double k) {
    return AAJNI.CAAPlanetPerihelionAphelion_Venus(k);
  }

  public static double EarthK(double Year) {
    return AAJNI.CAAPlanetPerihelionAphelion_EarthK(Year);
  }

  public static double EarthPerihelion(double k, boolean bBarycentric) {
    return AAJNI.CAAPlanetPerihelionAphelion_EarthPerihelion__SWIG_0(k, bBarycentric);
  }

  public static double EarthPerihelion(double k) {
    return AAJNI.CAAPlanetPerihelionAphelion_EarthPerihelion__SWIG_1(k);
  }

  public static double EarthAphelion(double k, boolean bBarycentric) {
    return AAJNI.CAAPlanetPerihelionAphelion_EarthAphelion__SWIG_0(k, bBarycentric);
  }

  public static double EarthAphelion(double k) {
    return AAJNI.CAAPlanetPerihelionAphelion_EarthAphelion__SWIG_1(k);
  }

  public static double MarsK(double Year) {
    return AAJNI.CAAPlanetPerihelionAphelion_MarsK(Year);
  }

  public static double Mars(double k) {
    return AAJNI.CAAPlanetPerihelionAphelion_Mars(k);
  }

  public static double JupiterK(double Year) {
    return AAJNI.CAAPlanetPerihelionAphelion_JupiterK(Year);
  }

  public static double Jupiter(double k) {
    return AAJNI.CAAPlanetPerihelionAphelion_Jupiter(k);
  }

  public static double SaturnK(double Year) {
    return AAJNI.CAAPlanetPerihelionAphelion_SaturnK(Year);
  }

  public static double Saturn(double k) {
    return AAJNI.CAAPlanetPerihelionAphelion_Saturn(k);
  }

  public static double UranusK(double Year) {
    return AAJNI.CAAPlanetPerihelionAphelion_UranusK(Year);
  }

  public static double Uranus(double k) {
    return AAJNI.CAAPlanetPerihelionAphelion_Uranus(k);
  }

  public static double NeptuneK(double Year) {
    return AAJNI.CAAPlanetPerihelionAphelion_NeptuneK(Year);
  }

  public static double Neptune(double k) {
    return AAJNI.CAAPlanetPerihelionAphelion_Neptune(k);
  }

  public CAAPlanetPerihelionAphelion() {
    this(AAJNI.new_CAAPlanetPerihelionAphelion(), true);
  }

}
