/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.naughter.aaplus;

public class CAAParallactic {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CAAParallactic(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CAAParallactic obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AAJNI.delete_CAAParallactic(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static double ParallacticAngle(double HourAngle, double Latitude, double delta) {
    return AAJNI.CAAParallactic_ParallacticAngle(HourAngle, Latitude, delta);
  }

  public static double EclipticLongitudeOnHorizon(double LocalSiderealTime, double ObliquityOfEcliptic, double Latitude) {
    return AAJNI.CAAParallactic_EclipticLongitudeOnHorizon(LocalSiderealTime, ObliquityOfEcliptic, Latitude);
  }

  public static double AngleBetweenEclipticAndHorizon(double LocalSiderealTime, double ObliquityOfEcliptic, double Latitude) {
    return AAJNI.CAAParallactic_AngleBetweenEclipticAndHorizon(LocalSiderealTime, ObliquityOfEcliptic, Latitude);
  }

  public static double AngleBetweenNorthCelestialPoleAndNorthPoleOfEcliptic(double Lambda, double Beta, double ObliquityOfEcliptic) {
    return AAJNI.CAAParallactic_AngleBetweenNorthCelestialPoleAndNorthPoleOfEcliptic(Lambda, Beta, ObliquityOfEcliptic);
  }

  public CAAParallactic() {
    this(AAJNI.new_CAAParallactic(), true);
  }

}
