/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.naughter.aaplus;

public class CAAPhysicalSun {
    private long swigCPtr;
    protected boolean swigCMemOwn;

    protected CAAPhysicalSun(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }

    protected static long getCPtr(CAAPhysicalSun obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                AAJNI.delete_CAAPhysicalSun(swigCPtr);
            }
            swigCPtr = 0;
        }
    }

    public static CAAPhysicalSunDetails Calculate(double JD) {
        return new CAAPhysicalSunDetails(AAJNI.CAAPhysicalSun_Calculate(JD), true);
    }

    public static double TimeOfStartOfRotation(int C) {
        return AAJNI.CAAPhysicalSun_TimeOfStartOfRotation(C);
    }

    public CAAPhysicalSun() {
        this(AAJNI.new_CAAPhysicalSun(), true);
    }

}
