/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.naughter.aaplus;

public class CAASaturnMoonsDetails {
    private long swigCPtr;
    protected boolean swigCMemOwn;

    protected CAASaturnMoonsDetails(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }

    protected static long getCPtr(CAASaturnMoonsDetails obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                AAJNI.delete_CAASaturnMoonsDetails(swigCPtr);
            }
            swigCPtr = 0;
        }
    }

    public void setSatellite1(CAASaturnMoonDetail value) {
        AAJNI.CAASaturnMoonsDetails_Satellite1_set(swigCPtr, this, CAASaturnMoonDetail.getCPtr(value), value);
    }

    public CAASaturnMoonDetail getSatellite1() {
        long cPtr = AAJNI.CAASaturnMoonsDetails_Satellite1_get(swigCPtr, this);
        return (cPtr == 0) ? null : new CAASaturnMoonDetail(cPtr, false);
    }

    public void setSatellite2(CAASaturnMoonDetail value) {
        AAJNI.CAASaturnMoonsDetails_Satellite2_set(swigCPtr, this, CAASaturnMoonDetail.getCPtr(value), value);
    }

    public CAASaturnMoonDetail getSatellite2() {
        long cPtr = AAJNI.CAASaturnMoonsDetails_Satellite2_get(swigCPtr, this);
        return (cPtr == 0) ? null : new CAASaturnMoonDetail(cPtr, false);
    }

    public void setSatellite3(CAASaturnMoonDetail value) {
        AAJNI.CAASaturnMoonsDetails_Satellite3_set(swigCPtr, this, CAASaturnMoonDetail.getCPtr(value), value);
    }

    public CAASaturnMoonDetail getSatellite3() {
        long cPtr = AAJNI.CAASaturnMoonsDetails_Satellite3_get(swigCPtr, this);
        return (cPtr == 0) ? null : new CAASaturnMoonDetail(cPtr, false);
    }

    public void setSatellite4(CAASaturnMoonDetail value) {
        AAJNI.CAASaturnMoonsDetails_Satellite4_set(swigCPtr, this, CAASaturnMoonDetail.getCPtr(value), value);
    }

    public CAASaturnMoonDetail getSatellite4() {
        long cPtr = AAJNI.CAASaturnMoonsDetails_Satellite4_get(swigCPtr, this);
        return (cPtr == 0) ? null : new CAASaturnMoonDetail(cPtr, false);
    }

    public void setSatellite5(CAASaturnMoonDetail value) {
        AAJNI.CAASaturnMoonsDetails_Satellite5_set(swigCPtr, this, CAASaturnMoonDetail.getCPtr(value), value);
    }

    public CAASaturnMoonDetail getSatellite5() {
        long cPtr = AAJNI.CAASaturnMoonsDetails_Satellite5_get(swigCPtr, this);
        return (cPtr == 0) ? null : new CAASaturnMoonDetail(cPtr, false);
    }

    public void setSatellite6(CAASaturnMoonDetail value) {
        AAJNI.CAASaturnMoonsDetails_Satellite6_set(swigCPtr, this, CAASaturnMoonDetail.getCPtr(value), value);
    }

    public CAASaturnMoonDetail getSatellite6() {
        long cPtr = AAJNI.CAASaturnMoonsDetails_Satellite6_get(swigCPtr, this);
        return (cPtr == 0) ? null : new CAASaturnMoonDetail(cPtr, false);
    }

    public void setSatellite7(CAASaturnMoonDetail value) {
        AAJNI.CAASaturnMoonsDetails_Satellite7_set(swigCPtr, this, CAASaturnMoonDetail.getCPtr(value), value);
    }

    public CAASaturnMoonDetail getSatellite7() {
        long cPtr = AAJNI.CAASaturnMoonsDetails_Satellite7_get(swigCPtr, this);
        return (cPtr == 0) ? null : new CAASaturnMoonDetail(cPtr, false);
    }

    public void setSatellite8(CAASaturnMoonDetail value) {
        AAJNI.CAASaturnMoonsDetails_Satellite8_set(swigCPtr, this, CAASaturnMoonDetail.getCPtr(value), value);
    }

    public CAASaturnMoonDetail getSatellite8() {
        long cPtr = AAJNI.CAASaturnMoonsDetails_Satellite8_get(swigCPtr, this);
        return (cPtr == 0) ? null : new CAASaturnMoonDetail(cPtr, false);
    }

    public CAASaturnMoonsDetails() {
        this(AAJNI.new_CAASaturnMoonsDetails(), true);
    }

}
