/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.naughter.aaplus;

public class CAASolarEclipseDetails {
    private long swigCPtr;
    protected boolean swigCMemOwn;

    protected CAASolarEclipseDetails(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }

    protected static long getCPtr(CAASolarEclipseDetails obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                AAJNI.delete_CAASolarEclipseDetails(swigCPtr);
            }
            swigCPtr = 0;
        }
    }

    public CAASolarEclipseDetails() {
        this(AAJNI.new_CAASolarEclipseDetails(), true);
    }

    public void setBEclipse(boolean value) {
        AAJNI.CAASolarEclipseDetails_bEclipse_set(swigCPtr, this, value);
    }

    public boolean getBEclipse() {
        return AAJNI.CAASolarEclipseDetails_bEclipse_get(swigCPtr, this);
    }

    public void setTimeOfMaximumEclipse(double value) {
        AAJNI.CAASolarEclipseDetails_TimeOfMaximumEclipse_set(swigCPtr, this, value);
    }

    public double getTimeOfMaximumEclipse() {
        return AAJNI.CAASolarEclipseDetails_TimeOfMaximumEclipse_get(swigCPtr, this);
    }

    public void setF(double value) {
        AAJNI.CAASolarEclipseDetails_F_set(swigCPtr, this, value);
    }

    public double getF() {
        return AAJNI.CAASolarEclipseDetails_F_get(swigCPtr, this);
    }

    public void setU(double value) {
        AAJNI.CAASolarEclipseDetails_u_set(swigCPtr, this, value);
    }

    public double getU() {
        return AAJNI.CAASolarEclipseDetails_u_get(swigCPtr, this);
    }

    public void setGamma(double value) {
        AAJNI.CAASolarEclipseDetails_gamma_set(swigCPtr, this, value);
    }

    public double getGamma() {
        return AAJNI.CAASolarEclipseDetails_gamma_get(swigCPtr, this);
    }

    public void setGreatestMagnitude(double value) {
        AAJNI.CAASolarEclipseDetails_GreatestMagnitude_set(swigCPtr, this, value);
    }

    public double getGreatestMagnitude() {
        return AAJNI.CAASolarEclipseDetails_GreatestMagnitude_get(swigCPtr, this);
    }

}
