/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.naughter.aaplus;

public class CAASidereal {
    private long swigCPtr;
    protected boolean swigCMemOwn;

    protected CAASidereal(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }

    protected static long getCPtr(CAASidereal obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                AAJNI.delete_CAASidereal(swigCPtr);
            }
            swigCPtr = 0;
        }
    }

    public static double MeanGreenwichSiderealTime(double JD) {
        return AAJNI.CAASidereal_MeanGreenwichSiderealTime(JD);
    }

    public static double ApparentGreenwichSiderealTime(double JD) {
        return AAJNI.CAASidereal_ApparentGreenwichSiderealTime(JD);
    }

    public CAASidereal() {
        this(AAJNI.new_CAASidereal(), true);
    }

}
