/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.naughter.aaplus;

public class CAAVenus {
    private long swigCPtr;
    protected boolean swigCMemOwn;

    protected CAAVenus(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }

    protected static long getCPtr(CAAVenus obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                AAJNI.delete_CAAVenus(swigCPtr);
            }
            swigCPtr = 0;
        }
    }

    public static double EclipticLongitude(double JD) {
        return AAJNI.CAAVenus_EclipticLongitude(JD);
    }

    public static double EclipticLatitude(double JD) {
        return AAJNI.CAAVenus_EclipticLatitude(JD);
    }

    public static double RadiusVector(double JD) {
        return AAJNI.CAAVenus_RadiusVector(JD);
    }

    public CAAVenus() {
        this(AAJNI.new_CAAVenus(), true);
    }

}
