/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.projectpluto.astro;

class astroJNI {
    public final static native void FixedBrightnessData_zenithAngMoon_set(long jarg1, FixedBrightnessData jarg1_, double jarg2);

    public final static native double FixedBrightnessData_zenithAngMoon_get(long jarg1, FixedBrightnessData jarg1_);

    public final static native void FixedBrightnessData_zenithAngSun_set(long jarg1, FixedBrightnessData jarg1_, double jarg2);

    public final static native double FixedBrightnessData_zenithAngSun_get(long jarg1, FixedBrightnessData jarg1_);

    public final static native void FixedBrightnessData_moonElongation_set(long jarg1, FixedBrightnessData jarg1_, double jarg2);

    public final static native double FixedBrightnessData_moonElongation_get(long jarg1, FixedBrightnessData jarg1_);

    public final static native void FixedBrightnessData_htAboveSeaInMeters_set(long jarg1, FixedBrightnessData jarg1_, double jarg2);

    public final static native double FixedBrightnessData_htAboveSeaInMeters_get(long jarg1, FixedBrightnessData jarg1_);

    public final static native void FixedBrightnessData_latitude_set(long jarg1, FixedBrightnessData jarg1_, double jarg2);

    public final static native double FixedBrightnessData_latitude_get(long jarg1, FixedBrightnessData jarg1_);

    public final static native void FixedBrightnessData_temperatureInC_set(long jarg1, FixedBrightnessData jarg1_, double jarg2);

    public final static native double FixedBrightnessData_temperatureInC_get(long jarg1, FixedBrightnessData jarg1_);

    public final static native void FixedBrightnessData_relativeHumidity_set(long jarg1, FixedBrightnessData jarg1_, double jarg2);

    public final static native double FixedBrightnessData_relativeHumidity_get(long jarg1, FixedBrightnessData jarg1_);

    public final static native void FixedBrightnessData_year_set(long jarg1, FixedBrightnessData jarg1_, double jarg2);

    public final static native double FixedBrightnessData_year_get(long jarg1, FixedBrightnessData jarg1_);

    public final static native void FixedBrightnessData_month_set(long jarg1, FixedBrightnessData jarg1_, double jarg2);

    public final static native double FixedBrightnessData_month_get(long jarg1, FixedBrightnessData jarg1_);

    public final static native long new_FixedBrightnessData();

    public final static native void delete_FixedBrightnessData(long jarg1);

    public final static native void AngularBrightnessData_zenithAngle_set(long jarg1, AngularBrightnessData jarg1_, double jarg2);

    public final static native double AngularBrightnessData_zenithAngle_get(long jarg1, AngularBrightnessData jarg1_);

    public final static native void AngularBrightnessData_distMoon_set(long jarg1, AngularBrightnessData jarg1_, double jarg2);

    public final static native double AngularBrightnessData_distMoon_get(long jarg1, AngularBrightnessData jarg1_);

    public final static native void AngularBrightnessData_distSun_set(long jarg1, AngularBrightnessData jarg1_, double jarg2);

    public final static native double AngularBrightnessData_distSun_get(long jarg1, AngularBrightnessData jarg1_);

    public final static native long new_AngularBrightnessData();

    public final static native void delete_AngularBrightnessData(long jarg1);

    public final static native int VisLimit_setBrightnessParams(long jarg1, VisLimit jarg1_, long jarg2, FixedBrightnessData jarg2_);

    public final static native int VisLimit_computeSkyBrightness(long jarg1, VisLimit jarg1_, long jarg2, AngularBrightnessData jarg2_);

    public final static native double VisLimit_computeLimitingMag(long jarg1, VisLimit jarg1_);

    public final static native int VisLimit_computeExtinction(long jarg1, VisLimit jarg1_);

    public final static native void VisLimit_setMask(long jarg1, VisLimit jarg1_, int jarg2);

    public final static native double VisLimit_getK(long jarg1, VisLimit jarg1_, long jarg2);

    public final static native double VisLimit_getBrightness(long jarg1, VisLimit jarg1_, long jarg2);

    public final static native double VisLimit_getExtinction(long jarg1, VisLimit jarg1_, long jarg2);

    public final static native long new_VisLimit();

    public final static native void delete_VisLimit(long jarg1);
}
